### ISSUE TITLE
incoming messages from subscribed channels

### ISSUE THREAD

**Issue by manylov** [zerobias/telegram-mtproto#174] opened 2018-05-16 10:58 UTC
Hi, what is the way to receive messages? can't find any info

**Comment by Novpic** [comment] 2018-06-19 21:10
version 3.1.3
Im using this listener for receiving the updates...
`client.bus.untypedMessage.observe( (data)=>{}
);`
here i check if in data.message have updates or update
then if it the update or updates has this attribute _:updateChannelMessageViews 
this one shows that there is a new message in a channel and shows the channel id and the message id
then i call  

                     
`client("channels.getMessages",{channel:
    {_: 'inputPeerChannel',
         channel_id:THECHANNELID ,access_hash: 'YOURHASH'},
          id:[MESSAGEID]
});`

this do a request and then the way of accessing this request is by catching it by this other listener
at the same level of the first client.bus.untypedMessage.observe()

`client.bus.rpcResult.observe((data)=>{
     console.log(data)
});`


this is suppose to work, but right now i have some issues calling the client request inside the first listener, this will help you a little.

IF SOMEONE CAN HELP US BOUTH IT WILL BE GREAT :)

**Comment by goodmind** [comment] 2018-06-22 15:14
Duplicate of #40

**Closed** 2018-06-22 15:14 UTC
Labels: Type: Duplicate
