### ISSUE TITLE
'units' variable undefined in /telegram-mtproto/lib/state/reducer/index.js:89

### ISSUE THREAD

**Issue by dundas** [zerobias/telegram-mtproto#107] opened 2017-10-14 17:02 UTC
Hi guys i'm getting the following error:

`
/app/node_modules/telegram-mtproto/lib/state/reducer/index.js:89
  var onlyAPI = units => units.filter(p => p.flags.api && p.api.resolved);
                                                               ^

TypeError: Cannot read property 'resolved' of undefined
`
I'm calling this from the following code sample:

`const { MTProto } =  require('telegram-mtproto');

const phone = '+123456789'
const api = {
  invokeWithLayer: 0xda9b0d0d,
  layer          : 57,
  initConnection : 0x69796de9,
  api_id         : 123456,
  app_version    : '1.0.1',
  lang_code      : 'en'
}

const server = {
  dev: true //We will connect to the test server.
}           //Any empty configurations fields can just not be specified

const app = {
  storage: new Storage('./storage.json')
 }  

const telegram = MTProto({ api, server ,app})

async function connect(){
  const { phone_code_hash } = await client('auth.sendCode', {
    phone_number  : phone,
    current_number: false,
    api_id        : 123456,
    api_hash      : 'xxxxxxxx'
  })

  //console.log('signed as ', user)
}

connect()`

I've check to find where units is defined and I can't find it anywhere.  I've replaced sensitive information. 

Thanks for any pointers.

**Comment by OwnageIsMagic** [comment] 2017-10-15 04:51
Hello, Github uses slightly different markdown dialect
For code blocks use 3 backticks (`` ``` ``)
https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting

**Comment by goodmind** [comment] 2017-10-15 08:54
@OwnageIsMagic this is error in lib, not his

**Comment by goodmind** [comment] 2017-10-15 08:55
Duplicate of #96

**Closed** 2017-10-15 08:55 UTC
Labels: Type: Duplicate

**Comment by dundas** [comment] 2017-10-15 09:19
Thanks @goodmind any idea of how to fix this?

**Comment by goodmind** [comment] 2017-10-15 09:46
@zerobias working on it I think

**Comment by OwnageIsMagic** [comment] 2017-10-16 06:18
@goodmind I know, but @dundas had some troubles with javascript
