### ISSUE TITLE
how to catch exception

### ISSUE THREAD

**Issue by dmitrdv** [zerobias/telegram-mtproto#111] opened 2017-10-29 04:45 UTC
Hello!

I used "telegram-mtproto": "^3.2.11". Sometimes I get error:
[635.575] Error 500 RPC_CALL_FAIL 2 2

This errors are happened here \telegram-mtproto\es\service\api-manager\index.js:
```js
req.performRequest().then(deferred.resolve, function (error) {
        var deferResolve = deferred.resolve;
        var apiSavedNet = _ref4;
        var apiRecall = _ref5;
        console.error(dTime(), 'Error', error.code, error.type, baseDcID, dcID);

        return switchErrors(error, options, dcID, baseDcID)(error, options, dcID, _this.emit, rejectPromise, requestThunk, apiSavedNet, apiRecall, deferResolve, _this.mtpInvokeApi, _this.storage);
      }).catch(rejectPromise);
```

I cannot catch that exception in my code in following way:
```js
try {
  res = await client('messages.getHistory', options);
} catch (ex) {
  logger.error(ex);
}
```

Could you tell me please, what is the right way to process exception that can occured during processing request?

**Comment by agogex** [comment] 2017-11-06 11:27
I have the same problem. Any suggestion how to resolve this problem?

**Comment by agogex** [comment] 2017-11-07 11:29
When i get FLOOD_WAIT error this one is logs silent to console not to catch section.
I need handle this moment for change client to another not banned, but i can't make this.
How can i catch this errors?
```javascript
--- request error --- request.js:34
{
  _:"rpc_error"
  error_code:420
  error_message:"FLOOD_WAIT_77778"
}
```

**Comment by goodmind** [comment] 2017-11-07 16:03
Duplicate of #103

**Closed** 2017-11-07 16:03 UTC
Labels: Type: Duplicate
