### ISSUE TITLE
Using TCP tunneling connection for faster updates

### ISSUE THREAD

**Issue by JackPoteYes** [zerobias/telegram-mtproto#87] opened 2017-09-14 11:27 UTC
It is written that Tl's api supports TCP tunneling instead of HTTP requests, in order to receive any new message ASAP. So no need to request the server in order to update the messages.
Where to put this configuration parameter ?
Any example ?

I need to read a message in a known interval of time, where each milisecond counts.

Thank you

**Comment by wfjsw** [comment] 2017-09-14 14:55
Duplicate of #1

**Closed** 2017-09-15 06:29 UTC
Labels: Type: Duplicate
