### ISSUE TITLE
Log out API returning a 502 error

### ISSUE THREAD

**Issue by andela-oadeniran** [zerobias/telegram-mtproto#114] opened 2017-11-06 16:43 UTC
```js
router.post('/logout', async function(req, res, next) {
  try {
   const  loggedOut  = await client('auth.logOut');
    if (!loggedOut) {
       res.send("Issues with logging out");
     }
    res.send("Successfully Logged out");
  } catch (error) {
    res.send(error);
 }
})
```
I am trying to map a logout route but it seems to log out but returns a 502 error with log.
encrypted request failed { Error: MT[406] NETWORK_BAD_REQUEST: https://venus.web.telegram.org/apiw_test1

**Comment by OwnageIsMagic** [comment] 2017-11-07 01:25
Code after `return` statement has no effect

**Comment by andela-oadeniran** [comment] 2017-11-07 07:39
Got that @OwnageIsMagic but the main issue is the logout throws an uncaught exception.

**Comment by andela-oadeniran** [comment] 2017-11-07 16:39
Still having the same issue refactored the code. Now this is what I have
router.post('/logout', async function(req, res, next) {
  try {
    const loggedOut  = await client('auth.logOut', {});
    if (!loggedOut) {
      res.send("Issues with logging out");
    }
    res.send("Successfully Logged out");
  } catch (error) {
    res.send(error);
  }
});

**Comment by andela-oadeniran** [comment] 2017-11-07 16:41
Tried what was suggested on this [issue](https://github.com/zerobias/telegram-mtproto/issues/81) but upgrading to version3 results in some other errors

**Comment by goodmind** [comment] 2017-11-07 16:59
You can't catch error?

**Comment by andela-oadeniran** [comment] 2017-11-07 17:05
The error/exception been thrown is not caught in the try and catch block.

**Comment by goodmind** [comment] 2017-11-07 20:00
Duplicate of #103

**Closed** 2017-11-07 20:00 UTC
Labels: Type: Duplicate
