### ISSUE TITLE
How to Update Handling?

### ISSUE THREAD

**Issue by JosefJezek** [zerobias/telegram-mtproto#136] opened 2017-12-28 14:07 UTC
Could you add support for easy update handling?

As pyrogram lib...

```py
def callback(update):
    print(update)

client = Client(session_name="example")
client.set_update_handler(callback)
```

https://github.com/pyrogram/pyrogram/wiki/Update-Handling

Thank you :wink:

**Comment by danog** [comment] 2017-12-28 14:56
github.com/danog/MadelineProto supports update handling, secret chat, phone calls, and much more!
Why don't you check it out ;)

**Comment by goodmind** [comment] 2018-06-22 15:34
Duplicate of #40

**Closed by goodmind** 2018-06-22 15:34 UTC
Labels: Priority: High
