### ISSUE TITLE
FLOOD_WAIT_79183 error when invoking auth.sendCode method

### ISSUE THREAD

**Issue by royalrover** [zerobias/telegram-mtproto#172] opened 2018-05-13 08:21 UTC
when I invoke the method
```
 const { phone_code_hash } = await client('auth.sendCode', {
            phone_number  : phone.num,
            current_number: false,
            api_id        : api.api_id,
            api_hash      : api_hash
        })
```
I got an error. The stack is
```
telegram error FLOOD_WAIT_79183 Error: FLOOD_WAIT_79183
    at Function.of (/Users/young/github/telegram-demo/node_modules/telegram-mtproto/lib/error.js:77:12)
    at detectErrors (/Users/young/github/telegram-demo/node_modules/telegram-mtproto/lib/state/epic/task.js:154:37)
    at action.thru.thru.map.combine.map.val (/Users/young/github/telegram-demo/node_modules/telegram-mtproto/lib/state/epic/task.js:46:56)
    at /Users/young/github/telegram-demo/node_modules/@most/prelude/dist/index.js:202:14
    at MapSink.event (/Users/young/github/telegram-demo/node_modules/most/lib/fusion/Map.js:71:22)
    at CombineSink.event (/Users/young/github/telegram-demo/node_modules/most/lib/combinator/combine.js:131:15)
    at IndexSink.event (/Users/young/github/telegram-demo/node_modules/most/lib/sink/IndexSink.js:28:13)
    at MapSink.event (/Users/young/github/telegram-demo/node_modules/most/lib/fusion/Map.js:71:13)
    at MulticastSource.event (/Users/young/github/telegram-demo/node_modules/@most/multicast/dist/multicast.js:82:17)
    at SliceSink.event (/Users/young/github/telegram-demo/node_modules/most/lib/combinator/slice.js:120:13)
    at tryEvent (/Users/young/github/telegram-demo/node_modules/@most/multicast/dist/multicast.js:24:10)
    at HoldSubjectSource.event (/Users/young/github/telegram-demo/node_modules/@most/multicast/dist/multicast.js:85:5)
    at HoldSubjectSource.event (/Users/young/github/telegram-demo/node_modules/most-subject/lib/commonjs/sources/HoldSubjectSource.js:28:39)
    at PropagateTask.emit [as _run] (/Users/young/github/telegram-demo/node_modules/most/lib/scheduler/PropagateTask.js:58:8)
    at PropagateTask.run (/Users/young/github/telegram-demo/node_modules/most/lib/scheduler/PropagateTask.js:43:8)
    at ScheduledTask.run (/Users/young/github/telegram-demo/node_modules/most/lib/scheduler/ScheduledTask.js:20:20)
    at runTask (/Users/young/github/telegram-demo/node_modules/most/lib/task.js:18:17)
    at runTasks (/Users/young/github/telegram-demo/node_modules/most/lib/scheduler/Timeline.js:80:7)
    at Timeline.runTasks (/Users/young/github/telegram-demo/node_modules/most/lib/scheduler/Timeline.js:69:20)
    at Scheduler._runReadyTasks (/Users/young/github/telegram-demo/node_modules/most/lib/scheduler/Scheduler.js:107:17)
    at Asap.Scheduler._runReadyTasksBound [as f] (/Users/young/github/telegram-demo/node_modules/most/lib/scheduler/Scheduler.js:29:10)
    at Asap.run (/Users/young/github/telegram-demo/node_modules/most/lib/scheduler/ClockTimer.js:32:30)
    at runTask (/Users/young/github/telegram-demo/node_modules/most/lib/task.js:18:17)
From previous event:
    at exports.blueDefer (/Users/young/github/telegram-demo/node_modules/telegram-mtproto/lib/util/defer.js:28:17)
    at new ApiRequest (/Users/young/github/telegram-demo/node_modules/telegram-mtproto/lib/service/main/request.js:30:34)
    at /Users/young/github/telegram-demo/node_modules/telegram-mtproto/lib/service/api-manager/index.js:237:20
    at Generator.next (<anonymous>)
    at step (/Users/young/github/telegram-demo/node_modules/telegram-mtproto/lib/service/api-manager/index.js:62:191)
    at /Users/young/github/telegram-demo/node_modules/telegram-mtproto/lib/service/api-manager/index.js:62:437
    at new Promise (<anonymous>)
    at /Users/young/github/telegram-demo/node_modules/telegram-mtproto/lib/service/api-manager/index.js:62:99
    at ApiManager.mtpInvokeApi (/Users/young/github/telegram-demo/node_modules/telegram-mtproto/lib/service/api-manager/index.js:259:7)
    at telegram (/Users/young/github/telegram-demo/node_modules/telegram-mtproto/lib/service/main/wrap.js:23:16)
    at connect (/Users/young/github/telegram-demo/my.js:56:43)
    at <anonymous>
```
I cannot find related doc, what does the error code mean?

**Comment by nagashik** [comment] 2018-05-14 17:42
you tried to use this method too often (it allows to use 200 times per day)
now you shoul wait "FLOOD_WAIT_79183" - 79183 seconds before it allows to use this method for your user again

**Comment by royalrover** [comment] 2018-05-15 01:44
thank you very much, but I did not invoke this method exceed 20 times. But once wait for some hours, this error will disappear

**Comment by goodmind** [comment] 2018-06-22 15:24
Duplicate of #125

**Closed by goodmind** 2018-06-22 15:24 UTC
Labels: Type: Bug
