### ISSUE TITLE
force to connect via  specific DC

### ISSUE THREAD

**Issue by adplaygit** [zerobias/telegram-mtproto#70] opened 2017-08-14 16:51 UTC
hi 
i want to connect via production dc that provided by telegram 
dc 2   149.154.167.50    443
i tested it with telegram-mtproto@3.1.3  and  telegram-mtproto@3.0.8  but still cant understand logic of this api .
it seems that this api automatically change and choose dc id and address

problem number 2  i also some times i  get this error in auth.sendCode
NETWORK_MIGRATE_5
but i cant connect to dc 5 !!!

please help me @zerobias  @leonerd  @goodmind 
thank you

**Comment by wfjsw** [comment] 2017-08-15 03:45
Duplicate of #43

**Closed** 2019-07-12 16:28 UTC
Labels: Priority: High
