### ISSUE TITLE
no any answer

### ISSUE THREAD

**Issue by nagashik** [zerobias/telegram-mtproto#171] opened 2018-05-10 13:41 UTC
code preview

`
	"use strict";

	var MTProto = require("telegram-mtproto").MTProto;
	var number                                   = '';
	console.log("Calling auth.sendCode on number = " + number);

	var APP                                      = {
		id:      99371,
		hash:    "06ffd2bf34db6b1edb38ec0a6518ca65",
		version: "0.0.1",
		lang:    "en",
	};

	var client                                   = MTProto({
		api: {
			layer:       57,
			api_id:      APP.id,
			app_version: APP.version,
			lang_code:   APP.lang,
		},
		server: {
			webogram: true,
			dev:      false
		},
	});

	client("auth.sendCode", {
		phone_number:   number,
		current_number: true,
		api_id:         APP.id,
		api_hash:       APP.hash,
	}).then((result)                             => {
		console.log("sendCode succeeded:", result);
		process.exit(0);
	});
`

start this script using: node test.js

and absolutely nothing happens
try to make it works all over the day. but can't solve the problem
used 3 different servers

it works for me about 2 weeks ago. and I could use telegram-mtproto
but no it doesn't work. and I couldn't understand what should I do with it

use the last 3.2.11 version

**Comment by OwnageIsMagic** [comment] 2018-05-12 12:12
telegram blocked in Russia and Iran

**Comment by nagashik** [comment] 2018-05-14 17:41
I know about blocking in Russia and Iran
I checked it from Austrian and Holland servers
the same truble. it doesn't work at all
@OwnageIsMagic @royalrover you want to say that 3.2.11 works perfect for both of you?

**Comment by bintoll** [comment] 2018-05-15 08:30
+1 no answer

**Comment by KylinWu** [comment] 2018-05-17 03:45
Same issue

**Comment by royalrover** [comment] 2018-05-17 06:59
my lib version is 3.1.3, and I modify the dc instead of the original

**Comment by nagashik** [comment] 2018-05-17 08:50
@royalrover how to install 3.1.3 version and how to change DC?
what IP adress did you use for DC?

**Comment by KylinWu** [comment] 2018-05-18 02:53
@nagashik 
`npm install telegram-mtproto@3.1.3 --save`

**Comment by esindger** [comment] 2018-06-10 14:45
Same issue in 3.2.11, but in 3.2.06 is working as expected

**Comment by goodmind** [comment] 2018-06-22 15:21
Duplicate of #103

**Closed by goodmind** 2018-06-22 15:21 UTC
