### ISSUE TITLE
Duplication / flooding of ping messages

### ISSUE THREAD

**Issue by Lord-Protector** [zerobias/telegram-mtproto#31] opened 2017-04-04 05:42 UTC
I use you lib as layer for hybrid bot that use Bot API and TG API simultaneously (because of lib has not update manager). But after some hours (4-5) I got many error like `NETWORK_BAD_REQUEST`, `Unhandled rejection undefined` etc. Is it okay or it's normal for beta state?
```
Encrypted request failed { Error: MT[406] NETWORK_BAD_REQUEST: http://149.154.167.51/apiw1
    at MTError (\node_modules\telegram-mtproto\lib\error.js:13:5)
    at ErrorBadRequest (\node_modules\telegram-mtproto\lib\error.js:30:5)
    at NetworkerThread._ref20 (\node_modules\telegram-mtproto\lib\service\networker\index.js:1050:40)
    at throw (native)
    at step (\node_modules\telegram-mtproto\lib\service\networker\index.js:62:202)
    at \node_modules\telegram-mtproto\lib\service\networker\index.js:62:424
    at tryCatcher (\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
  code: 406,
  type: 'NETWORK_BAD_REQUEST',
  originalError: 
   { Error: Request failed with status code 429
       at createError (\node_modules\axios\lib\core\createError.js:15:15)
       at settle (\node_modules\axios\lib\core\settle.js:18:12)
       at IncomingMessage.handleStreamEnd (\node_modules\axios\lib\adapters\http.js:186:11)
       at emitNone (events.js:91:20)
       at IncomingMessage.emit (events.js:185:7)
       at endReadableNT (_stream_readable.js:974:12)
       at _combinedTickCallback (internal/process/next_tick.js:80:11)
       at process._tickDomainCallback (internal/process/next_tick.js:128:9)
     config: 
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'post',
        responseType: 'arraybuffer',
        url: 'http://149.154.167.51/apiw1',
        data: ArrayBuffer { byteLength: 904 } },
     response: 
      { status: 429,
        statusText: 'Too Many Requests',
        headers: [Object],
        config: [Object],
        request: [Object],
        data: <Buffer 3c 68 74 6d 6c 3e 0d 0a 3c 68 65 61 64 3e 3c 74 69 74 6c 65 3e 34 32 39 20 54 6f 6f 20 4d 61 6e 79 20 52 65 71 75 65 73 74 73 3c 2f 74 69 74 6c 65 3e ... > } } }
```
and:
```
. . .
Unhandled rejection undefined
Unhandled rejection undefined
Unhandled rejection undefined
Unhandled rejection undefined
Unhandled rejection undefined
Unhandled rejection undefined
Unhandled rejection undefined
Unhandled rejection undefined
Unhandled rejection undefined
Unhandled rejection undefined
Unhandled rejection undefined
Unhandled rejection undefined
Unhandled rejection undefined
Unhandled rejection undefined
Unhandled rejection undefined
. . .
```

**Comment by Lord-Protector** [comment] 2017-04-04 13:38
Full logs: https://gist.github.com/Lord-Protector/25ab216eb905ef2252c7bf0e41f7c0c9

**Comment by zerobias** [comment] 2017-04-04 22:19
Oh, thanks, I think I know where is the problem

**Comment by Lord-Protector** [comment] 2017-04-05 04:49
@zerobias Also sometime I get randomly two errors:
`[MT] Bad server salt for invalid message` and `[MT] Bad msg notification for invalid message`

Full log for example:
https://gist.github.com/Lord-Protector/158a4e04fb70e66e42d3129a27cfa54b

**Comment by zerobias** [comment] 2017-04-07 18:59
Fixed in https://github.com/zerobias/telegram-mtproto/commit/4019b2d9413a43523254def8afa90d0cbe8d10b1

I'll leave it open for a while. Needs to make sure that the problem is solved.

**Comment by Lord-Protector** [comment] 2017-04-07 19:02
Wait in NPM to test.

**Comment by zerobias** [comment] 2017-04-07 19:06
`npm install --save telegram-mtproto@alpha`

https://github.com/zerobias/telegram-mtproto/issues/37#issuecomment-292621584

**Comment by Lord-Protector** [comment] 2017-04-07 19:07
Oh, thanks 👍

**Closed** 2017-04-08 21:07 UTC
Labels: Priority: High

**Comment by vodniciarv** [comment] 2018-01-25 15:52
In version `^2.2.8` error still exists?

**Comment by koloboid** [comment] 2018-05-11 07:43
Still exists in 2.2.8 and really annoying. Any workaround?
