### ISSUE TITLE
TypeError: Cannot read property 'resolved' of undefined

### ISSUE THREAD

**Issue by Fuzzyma** [zerobias/telegram-mtproto#144] opened 2018-01-13 18:07 UTC
In `lib/state/reducer/index.js:89:64` you have the following line:

```js
var onlyAPI = units => units.filter(p => p.flags.api && p.api.resolved);
```

ok - in your code its completely somewhere else. No idea what black magic you use. So here is a link to the line: https://github.com/zerobias/telegram-mtproto/blob/208b5ba158552e0848822279b5273e4f104d8489/packages/telegram-mtproto/src/state/reducer/index.js#L110-L111

The script dies here because there is no attribute `api` in `payload` and so it tries to access a member of undefined. I looked into the payload object and couldnt find anything related to `resolved`:

```js
{ flags:
     { api: false,
       inner: false,
       container: true,
       incoming: true,
       methodResult: false,
       body: false,
       error: false },
    incoming: { timestamp: 1515866479195 },
    container: { contains: [Array] },
    id: '#######',
    seq: 6,
    session: [ ###### ],
    dc: 2,
    uid: '#######' }
```

So what is `p.api.resolved` for?

**Comment by goodmind** [comment] 2018-01-14 15:50
Duplicate of #96

**Comment by Fuzzyma** [comment] 2018-01-14 15:51
In this case I am sorry!

**Closed** 2018-01-14 15:50 UTC
Labels: Type: Duplicate

**Comment by goodmind** [comment] 2018-01-14 15:56
no problem
